---
title: 'Pre-process email data'
date: 'September 1, 2022'
author: 'Maurizio P. De Marchi'
output:
html_document:
df_print: paged
theme: readable
toc: true
toc_float: true
pdf_document: default
editor_options:
chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      tidy.opts = list(width.cutoff = 60),
                      tidy = TRUE)
library(tidyverse)
library(stringi)
library(plyr)
```

Here we are going to further preprocess the data in order to have a single final dataset
```{r}

#Scam dataset

file_names <- dir(path = "./datasets/scam", full.names = T, include.dirs = FALSE)
file_names <- file_names[!file.info(file_names)$isdir]
scam_df <- do.call(rbind, lapply(file_names, read.csv))

#scam_df$From <- str_extract(string = scam_df$From, pattern = "<(.*?)>")
#scam_df$From <- str_replace(string = scam_df$From, pattern = "<", replacement = '')
#scam_df$From <- str_replace(string = scam_df$From, pattern = ">", replacement = '')

na_indexes <- unique(
  c(
    which(is.na(scam_df$From)),
    which(stri_isempty(scam_df$Date)),
    which(stri_isempty(scam_df$Text))
))# check for NAs in From, Date and Text. Subject can be empty



# remove csv index and empty strings
if(length(na_indexes) != 0){
   scam_df <- scam_df[-na_indexes, 2:5]
} else {
  scam_df <- scam_df[, 2:5]
}

scam_df$Text <- stringi::stri_trans_general(scam_df$Text, "latin-ascii")
scam_df$Subject <- stringi::stri_trans_general(scam_df$Subject, "latin-ascii")

# add the y column
scam_df$y <- rep(as.factor("scam"), nrow(scam_df))
```

```{r}
file_names <- dir(path = "./datasets/scam/2", full.names = T, include.dirs = FALSE)
file_names <- file_names[!file.info(file_names)$isdir]
scam_df2 <- do.call(rbind, lapply(file_names, read.csv))

na_indexes <- unique(
  c(
    which(is.na(scam_df2$From)),
    which(stri_isempty(scam_df2$Date)),
    which(stri_isempty(scam_df2$Text))
))# check for NAs in From, Date and Text. Subject can be empty

# remove csv index and empty strings
if(length(na_indexes) != 0){
   scam_df2 <- scam_df2[-na_indexes, 2:5]
} else {
  scam_df2 <- scam_df2[, 2:5]
}


scam_df2$Text <- stringi::stri_trans_general(scam_df2$Text, "latin-ascii")
scam_df2$Subject <- stringi::stri_trans_general(scam_df2$Subject, "latin-ascii")

# add the y column
scam_df2$y <- rep(as.factor("scam"), nrow(scam_df2))
```

```{r}
scam_df <- rbind(scam_df, scam_df2)
rm(scam_df2)
```


```{r}
#non-scam dataset
file_names <- dir(path = "./datasets/pre-processed", full.names = T)
non_scam_df <- do.call(rbind, lapply(file_names, read.csv))
na_indexes <- unique(
  c(
    which(stri_isempty(non_scam_df$From)),
    which(stri_isempty(non_scam_df$Date)),
    which(stri_isempty(non_scam_df$Text)))
)# check for NAs in From, Date and Text. Subject can be empty

# remove csv index and empty strings
non_scam_df <- non_scam_df[-na_indexes, 2:5]

non_scam_df$Text <- stringi::stri_trans_general(non_scam_df$Text, "latin-ascii")
non_scam_df$Subject <- stringi::stri_trans_general(non_scam_df$Subject, "latin-ascii")

# add the y column
non_scam_df$y <- rep(as.factor("not-scam"), nrow(non_scam_df))
```

```{r}
# union
final_df <- rbind(scam_df, non_scam_df)

# date
d <- NULL
h <- NULL
dn <- NULL
m <- NULL


date_approximated<- function (value = "18:00:28")
{
  if(grepl(pattern = "\\.", x=value))
  {
    # we have another format
    ris <- unlist(str_split(value, pattern = "."))
  } else {
    value <- str_sub(value, start = 1, end = 5) # 18:00
  ris <- unlist(str_split(value, pattern = ":"))
  }


  # simplify hour
  tryCatch(
  {
    if(as.integer(ris[2]) > 45){
      ris <- as.integer(ris[1]) + 1}
    else{
      ris <- as.integer(ris[1])}
  },
    error = function(e) {
      print("Error while reading")
    })
  if(is.numeric(ris)){
    if(ris < 2000)
    {
      return(as.character(ris))
    }
  }

  return(NA)

}

for (s in final_df$Date) {
  s <- unlist(str_split(string = s, pattern = " "))  # es: Wed, 24 Dec 2003 18:00:28 -800 (CET)

  d <- c(d, str_sub(unlist(s)[2], start = 1, end = 3)) # days
  h <- c(h, date_approximated(s[6]))
  dn <- c(dn, s[3])
  m <- c(m, s[4])
}

final_df$Month <- m
final_df$Day_number <- dn
final_df$Day <- d
final_df$Hour <- h
final_df <- final_df[, -2]


#delete NA hour
na_indexes <- which(is.na(final_df$Hour))
final_df <- final_df[-na_indexes,]

# save
saveRDS(final_df, file = "datasets/final_df.rds")
# write.csv(final_df, file = "datasets/final_df.csv")
rm(na_indexes, file_names, non_scam_df, scam_df, h, s, d, dn, m)
```
```{r}
summary(as_tibble(final_df))
```
test
```{r}
test <- readRDS("datasets/final_df.rds")
```
```{r}
rm(test)
```
